-- =============================================
-- FOODIARY — Supabase Database Schema
-- Run this in Supabase SQL Editor
-- =============================================

-- 1. Products table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  description text,
  created_at timestamptz default now()
);

-- Seed default product
insert into products (name, price, description)
values ('Takoyaki 8 Ball', 15000, 'Takoyaki isi 8 bola per porsi');

-- 2. Orders table
create table orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  product_id bigint references products(id),
  quantity int not null default 1,
  total_price numeric not null default 0,
  payment_method text default 'cash', -- 'cash' | 'tf'
  shipping_fee numeric default 0,
  notes text,
  status text default 'process', -- 'process' | 'done'
  created_at timestamptz default now()
);

-- 3. Expenses table
create table expenses (
  id bigint generated by default as identity primary key,
  name text not null,
  amount int not null default 1,
  price numeric not null default 0,
  category text,
  notes text,
  created_at timestamptz default now()
);

-- 4. Open PO dates
create table open_po_dates (
  id bigint generated by default as identity primary key,
  date text not null unique, -- format: YYYY-MM-DD
  created_at timestamptz default now()
);

-- =============================================
-- Row Level Security (RLS)
-- Disable RLS for personal use (single user)
-- =============================================
alter table products disable row level security;
alter table orders disable row level security;
alter table expenses disable row level security;
alter table open_po_dates disable row level security;
